### ISSUE TITLE
java.lang.ArithmeticException: divide by zero RandomHelper.number(RandomHelper.java:31)

### ISSUE THREAD

**Issue by GalouM** [blocoio/faker#14]
When doing `faker.date.backward(1)` it can throw this expecetion
Random helper should probably protect from dividing by 0

```
java.lang.ArithmeticException: divide by zero
	at io.bloco.faker.helpers.RandomHelper.number(RandomHelper.java:31)
	at io.bloco.faker.components.Date.getRandomDate(Date.java:80)
	at io.bloco.faker.components.Date.between(Date.java:70)
	at io.bloco.faker.components.Date.backward(Date.java:56)
	at com.grouse.dr_bill.data.preferences.LoggingPreferencesTest.latestUpload_whenEmpty(LoggingPreferencesTest.kt:39)
```

**Comment by rickytribbia** [comment]
It happens in my app, too. Same crash

**Comment by rickytribbia** [comment]
#15
